Repository player-ui/player, pull requests merged in 2022-08, with the labels that each got.

#50 enhance error state deserialization & stacktrace logging in player view model
  WORKSPACE
  android/demo/BUILD
  android/player/src/main/java/com/intuit/player/android/lifecycle/PlayerViewModel.kt
  jvm/core/src/main/kotlin/com/intuit/player/jvm/core/player/state/PlayerFlowState.kt
  jvm/core/src/test/kotlin/com/intuit/player/jvm/core/player/HeadlessPlayerTest.kt
  jvm/core/src/test/kotlin/com/intuit/player/jvm/core/player/state/ErrorStateTest.kt
Labels: patch

#51 added templates to content navigation, fixed the link to reference as…
  docs/site/config/navigation.ts
  docs/site/pages/plugins/asset-provider.mdx
Labels: documentation

#55 fix IR backend for kotlinx serialization
  android/player/src/main/java/com/intuit/player/android/asset/RenderableAsset.kt
  plugins/reference-assets/android/src/main/java/com/intuit/player/android/reference/assets/collection/Collection.kt
  plugins/reference-assets/android/src/main/java/com/intuit/player/android/reference/assets/info/Info.kt
  plugins/reference-assets/android/src/main/java/com/intuit/player/android/reference/assets/input/Input.kt
Labels: patch

#27 set applitools env variables for iOS tests
  .circleci/config.yml
  android/build.bzl
  android/demo/src/androidTest/java/com/intuit/player/android/reference/demo/test/base/ApplitoolsTest.kt
  ios/packages/reference-assets/UITests/BaseTestCase.swift
  xcode/PlayerUI.xcodeproj/xcshareddata/xcschemes/PlayerUI-Example.xcscheme
  xcode/PlayerUI.xcodeproj/xcshareddata/xcschemes/PlayerUIUITests.xcscheme
Labels: patch, skip-release

#56 allow caching ios tests again
  .circleci/config.yml
Labels: patch, skip-release

#58 Fix the bin entry for the cli
  tools/cli/BUILD
  tools/cli/package.json
Labels: patch

#57 add local auto plugin to run bazel pod push after release
  .autorc
  .circleci/config.yml
  PlayerUI.podspec
  ios/packages/reference-assets/UITests/ActionAssetUITests.swift
  scripts/after-release-pod-push.js
  scripts/fetchArtifacts.sh
  scripts/parseArtifactJson.js
  scripts/release.sh
Labels: patch

#59 fix pod release plugin
  .autorc
  scripts/after-release-pod-push.js
Labels: patch

#61 move pod push to afterShipIt to have upload-assets finish first
  .autorc
  scripts/after-shipit-pod-push.js
Labels: patch

#62 try/catch pod push in plugin
  scripts/after-shipit-pod-push.js
Labels: patch

#63 dont use bazel to push since the stamping wont work after shipit
  scripts/after-shipit-pod-push.js
Labels: patch

#65 upgrade to xcode 13.4.1
  .circleci/config.yml
  WORKSPACE
Labels: patch

#70 split out test helper functionality so XCTest isn't a hard requirement
  PlayerUI.podspec
  generated.bzl
  ios/packages/internal-test-utils/Sources/HeadlessPlayerImpl.swift
  ios/packages/reference-assets/ViewInspector/SwiftUI/ActionAssetTests.swift
  ios/packages/reference-assets/ViewInspector/SwiftUI/CollectionAssetTests.swift
  ios/packages/reference-assets/ViewInspector/SwiftUI/InfoAssetTests.swift
  ios/packages/reference-assets/ViewInspector/SwiftUI/InputAssetTests.swift
  ios/packages/reference-assets/ViewInspector/SwiftUI/TextAssetTests.swift
  ios/packages/test-utils-core/Sources/AssetTestHelper.swift
  ios/packages/test-utils-core/Tests/AssetTestHelperTests.swift
  ios/packages/test-utils/Sources/unit-test/AssetUnitTestCaseBase.swift
  ios/packages/test-utils/Sources/unit-test/SwiftUIAssetUnitTestCase.swift
  ios/packages/test-utils/Tests/unit-test/AssetUnitTestCaseTests.swift
  ios/packages/test-utils/ViewInspector/unit-test/SwiftUIAssetUnitTestCaseTests.swift
  xcode/Podfile
  xcode/Podfile.lock
Labels: patch

#72 add delay before screenshotting for animations to finish
  ios/packages/reference-assets/UITests/ActionAssetUITests.swift
  ios/packages/reference-assets/UITests/BaseTestCase.swift
  ios/packages/reference-assets/UITests/CollectionAssetUITests.swift
  ios/packages/reference-assets/UITests/InfoAssetUITests.swift
  ios/packages/reference-assets/UITests/InputAssetUITests.swift
  ios/packages/reference-assets/UITests/TextAssetUITests.swift
Labels: patch

#75 Remove exit on error flag in release script
  scripts/release.sh
Labels: release

#76 Add algolia search to /latest/ site
  docs/BUILD
  docs/site/BUILD
  docs/site/components/AlgoliaSearch.tsx
  docs/site/components/Search.tsx
  docs/site/pages/_app.tsx
  package.json
  scripts/workspace-status.sh
  yarn.lock
Labels: documentation
