Repository player-ui/player, pull requests merged in 2022-12, with the labels that each got.

#106 Canary workflow
  .circleci/config.yml
  .github/workflows/canary.yml
Labels: skip-release

#109 Sync Latest Player Code
  WORKSPACE
  core/player/BUILD
  core/player/bundle.entry.js
  core/player/src/__tests__/helpers/expression.plugin.ts
  core/player/src/__tests__/player.test.ts
  core/player/src/__tests__/validation.test.ts
  core/player/src/__tests__/view.test.ts
  core/player/src/binding/resolver.ts
  core/player/src/controllers/data.ts
  core/player/src/controllers/validation/controller.ts
  core/player/src/data/model.ts
  core/player/src/expressions/__tests__/__snapshots__/parser.test.ts.snap
  core/player/src/expressions/__tests__/parser.test.ts
  core/player/src/expressions/__tests__/utils.test.ts
  core/player/src/expressions/evaluator.ts
  core/player/src/expressions/parser.ts
  core/player/src/expressions/types.ts
  core/player/src/expressions/utils.ts
  core/player/src/player.ts
  core/player/src/string-resolver/__tests__/index.test.ts
  core/player/src/string-resolver/index.ts
  core/player/src/validator/validation-middleware.ts
  core/player/src/view/plugins/string-resolver.ts
  docs/storybook/.storybook/preview.js
  docs/storybook/BUILD
  index.bzl
  package.json
  plugins/asset-transform/core/src/__tests__/index.test.ts
  plugins/auto-scroll/react/BUILD
  plugins/auto-scroll/react/src/__tests__/plugin.test.tsx
  plugins/auto-scroll/react/src/hooks.tsx
  plugins/auto-scroll/react/src/plugin.tsx
  plugins/beacon/core/src/beacon.ts
  plugins/beacon/core/src/index.test.ts
  plugins/check-path/core/src/index.test.ts
  plugins/check-path/core/src/index.ts
  plugins/check-path/react/src/__tests__/check-path.test.tsx
  plugins/check-path/react/src/hooks.tsx
  plugins/data-change-listener/core/src/index.test.ts
  plugins/data-change-listener/core/src/index.ts
  webpack.config.js
  yarn.lock
Labels: minor

#112 pin bazel version to 5.4.0
  .bazelversion
Labels: skip-release

#111 Deps/bump dependencies
  WORKSPACE
  index.bzl
  package.json
  yarn.lock
Labels: patch

#113 add bundle property to package for targets that produce webpack bundles
  index.bzl
Labels: patch
