Repository player-ui/player, pull requests merged in 2023-10, with the labels that each got.

#174 Update asset-provider.mdx
  docs/site/pages/plugins/asset-provider.mdx
Labels: documentation, skip-release, hacktoberfest

#139 Export InfoAsset as XLR View
  plugins/reference-assets/react/src/plugin.tsx
Labels: patch, skip-release

#189 Added note to input asset
  ios/packages/demo/Sources/MockFlows.swift
  ios/packages/reference-assets/Sources/SwiftUI/InfoAsset.swift
  ios/packages/reference-assets/Sources/SwiftUI/InputAsset.swift
  plugins/reference-assets/mocks/input/input-basic.json
Labels: skip-release, hacktoberfest

#194 [Issue 162] iOS: Add footer to info reference asset
  ios/packages/demo/Sources/MockFlows.swift
  ios/packages/reference-assets/Sources/SwiftUI/InfoAsset.swift
  ios/packages/reference-assets/ViewInspector/SwiftUI/InfoAssetTests.swift
  plugins/reference-assets/mocks/info/info-footer.json
Labels: skip-release, hacktoberfest, hacktoberfest-accepted

#191 Core: add Support For Segmented Assets
  plugins/auto-scroll/react/src/__tests__/plugin.test.tsx
  plugins/reference-assets/core/src/assets/info/__tests__/transform.test.ts
  plugins/reference-assets/core/src/assets/info/index.ts
  plugins/reference-assets/core/src/assets/info/transform.ts
  plugins/reference-assets/core/src/assets/info/types.ts
  plugins/reference-assets/core/src/plugin.ts
  plugins/reference-assets/mocks/info/info-basic.json
  plugins/reference-assets/react/src/assets/info/Info.tsx
Labels: hacktoberfest, hacktoberfest-accepted

#193 Sync Up To Latest
  .all-contributorsrc
  core/player/BUILD
  core/player/src/__tests__/validation.test.ts
  core/player/src/binding-grammar/__tests__/parser.test.ts
  core/player/src/binding-grammar/__tests__/test-utils/ast-cases.ts
  core/player/src/binding-grammar/custom/index.ts
  core/player/src/binding/index.ts
  core/player/src/binding/resolver.ts
  core/player/src/controllers/validation/controller.ts
  docs/site/pages/content/switches.mdx
  docs/site/pages/plugins/data-change-listener.mdx
  docs/storybook/.storybook/preview.js
  docs/storybook/.storybook/webpack.config.js
  docs/storybook/BUILD
  docs/storybook/src/Welcome.stories.mdx
  docs/storybook/src/components/StoryWrapper.tsx
  docs/storybook/src/reference-assets/Action.stories.mdx
  docs/storybook/src/reference-assets/Intro.stories.mdx
  package.json
  plugins/markdown/core/src/__tests__/__snapshots__/index.test.ts.snap
  plugins/markdown/core/src/__tests__/helpers/index.ts
  plugins/markdown/core/src/__tests__/index.test.ts
  plugins/markdown/core/src/index.ts
  plugins/markdown/core/src/types.ts
  plugins/markdown/core/src/utils/markdownParser.ts
  plugins/pubsub/core/src/plugin.ts
  plugins/pubsub/core/src/pubsub.ts
  plugins/reference-assets/mocks/BUILD
  plugins/reference-assets/mocks/action/action-basic.tsx
  plugins/reference-assets/mocks/action/action-transition-to-end.tsx
  react/player/src/asset/__tests__/index.test.tsx
  react/player/src/asset/index.tsx
  tools/storybook/BUILD
  tools/storybook/src/addons/appetize/index.tsx
  tools/storybook/src/addons/editor/index.tsx
  tools/storybook/src/addons/events/index.tsx
  tools/storybook/src/addons/index.tsx
  tools/storybook/src/addons/refresh/index.tsx
  tools/storybook/src/decorator/index.tsx
  tools/storybook/src/dsl/createDSLStory.tsx
  tools/storybook/src/dsl/index.ts
  tools/storybook/src/dsl/transpile.ts
  tools/storybook/src/index.ts
  tools/storybook/src/player/PlayerStory.tsx
  tools/storybook/src/player/hooks.ts
  tools/storybook/src/player/storybookReactPlayerPlugin.ts
  tools/storybook/src/player/useFlowSet.tsx
  tools/storybook/src/redux/index.tsx
  tools/storybook/src/state/hooks.ts
  tools/storybook/src/state/index.ts
  tools/storybook/src/types.ts
  yarn.lock
Labels: patch

#207 apply swift 6 warning fix to flaky iOS tests
  ios/packages/swiftui/Tests/ManagedPlayer/ManagedPlayerViewModelTests.swift
Labels: patch

#210 store cancellables in ManagedPlayerViewModelTests
  ios/packages/swiftui/Tests/ManagedPlayer/ManagedPlayerViewModelTests.swift
Labels: skip-release
