Repository player-ui/player, pull requests merged in 2023-11, with the labels that each got.

#214 Singular workflow for CI
  .circleci/config.yml
Labels: skip-release

#200 179/AndroidContributionGuide
  android/demo/README.md
Labels: documentation, skip-release

#209 iOS: remove strong self references in plugins
  ios/plugins/BaseBeaconPlugin/Sources/BaseBeaconPlugin.swift
  ios/plugins/BeaconPlugin/Sources/SwiftUIBeaconPlugin.swift
  ios/plugins/ExpressionPlugin/Sources/ExpressionPlugin.swift
  ios/plugins/ExternalActionPlugin/Sources/ExternalActionPlugin.swift
  ios/plugins/ExternalActionViewModifierPlugin/Sources/ExternalActionViewModifierPlugin.swift
  ios/plugins/MetricsPlugin/Sources/MetricsPlugin.swift
  ios/plugins/SwiftUICheckPathPlugin/Sources/SwiftUICheckPathPlugin.swift
  scripts/after-shipit-pod-push.js
Labels: patch

#218 fix iOS release, and fix script to show output properly
  BUILD.bazel
  scripts/after-shipit-pod-push.js
Labels: patch

#216 Return a Read Only Instance of the DataController on Player End State
  core/player/src/__tests__/data.test.ts
  core/player/src/controllers/data/controller.ts
  core/player/src/controllers/data/index.ts
  core/player/src/controllers/data/utils.ts
  core/player/src/controllers/index.ts
  core/player/src/controllers/view/controller.ts
  core/player/src/player.ts
  core/player/src/types.ts
Labels: patch

#195 Android: add label to collection
  plugins/reference-assets/android/src/androidTest/java/com/intuit/player/android/reference/assets/action/ActionTest.kt
  plugins/reference-assets/android/src/androidTest/java/com/intuit/player/android/reference/assets/collection/CollectionTest.kt
  plugins/reference-assets/android/src/androidTest/java/com/intuit/player/android/reference/assets/text/TextTest.kt
  plugins/reference-assets/android/src/main/java/com/intuit/player/android/reference/assets/collection/Collection.kt
  plugins/reference-assets/android/src/main/res/layout/collection.xml
Labels: hacktoberfest, hacktoberfest-accepted

#202 FirstTimeContributorGuide
  CONTRIBUTING.md
  newCONTRIBUTORS.md
Labels: documentation, skip-release

#197 Core Image Reference Asset
  docs/storybook/src/reference-assets/Image.stories.mdx
  docs/storybook/src/reference-assets/flows.ts
  plugins/reference-assets/core/src/assets/image/__tests__/transform.test.ts
  plugins/reference-assets/core/src/assets/image/index.ts
  plugins/reference-assets/core/src/assets/image/transform.ts
  plugins/reference-assets/core/src/assets/image/types.ts
  plugins/reference-assets/core/src/assets/index.ts
  plugins/reference-assets/core/src/plugin.ts
  plugins/reference-assets/mocks/image/image-basic.json
  plugins/reference-assets/mocks/image/image-with-accessibility.json
  plugins/reference-assets/mocks/image/image-with-caption.json
  plugins/reference-assets/mocks/image/image-with-placeholder.json
  plugins/reference-assets/react/src/assets/image/Image.tsx
  plugins/reference-assets/react/src/assets/image/index.tsx
  plugins/reference-assets/react/src/assets/index.tsx
  plugins/reference-assets/react/src/plugin.tsx
Labels: minor, hacktoberfest

#211 feat/decouple back button
  plugins/reference-assets/core/src/assets/action/__tests__/transform.test.ts
  plugins/reference-assets/core/src/assets/action/transform.ts
  plugins/reference-assets/core/src/assets/action/types.ts
  plugins/reference-assets/mocks/action/action-navigation.json
  plugins/reference-assets/react/src/assets/action/Action.tsx
Labels: patch

#225 Sync Up to Latest
  core/player/src/__tests__/validation.test.ts
  core/player/src/controllers/validation/controller.ts
  tools/storybook/src/redux/index.tsx
Labels: patch

#230 Pin @moncao-editor/react to non `.mjs` Only Version
  package.json
  yarn.lock
Labels: patch

#226 iOS: Update precompile script to source zshrc
  PlayerUI.podspec
  VERSION
  ios/packages/demo/Sources/MockFlows.swift
  ios/packages/reference-assets/UITests/BaseTestCase.swift
  scripts/release.sh
  xcode/Podfile.lock
Labels: patch

#239 Add better error messaging for failed expression eval and parsing
  core/player/BUILD
  core/player/src/expressions/__tests__/evaluator.test.ts
  core/player/src/expressions/evaluator.ts
  package.json
Labels: patch

#243 Update auto version. Filter release trigger from changelogs
  .autorc
  package.json
  yarn.lock
Labels: skip-release, internal

#238 Update broken link in contributing docs
  CONTRIBUTING.md
Labels: documentation, skip-release

#245 Add Automation ID to Error Element in Storybook
  tools/storybook/src/player/PlayerFlowSummary.tsx
Labels: patch

#246 Update ruby version in build
  .circleci/config.yml
Labels: skip-release, internal

#250 iOS: add SwiftUIPendingTransactionPlugin to reference asset dependencies
  PlayerUI.podspec
Labels: patch
