Repository player-ui/player, pull requests merged in 2023-01, with the labels that each got.

#115 add webpack bundles to js_library_data
  .circleci/config.yml
  index.bzl
  xcode/Podfile
Labels: patch

#119 Update default context for ManagedPlayer to use JSVirtualMachine
  ios/packages/swiftui/Sources/ManagedPlayer/ManagedPlayer.swift
Labels: patch

#122 [iOS] genericize wrapper data decoding beyond metaData
  ios/packages/core/Sources/Types/Assets/Wrappers.swift
  ios/packages/swiftui/Sources/types/assets/WrappedAsset.swift
  ios/packages/swiftui/Tests/SwiftUIRegistryTests.swift
  xcode/Podfile.lock
Labels: minor

#123 dont try to push pod if its a canary release
  scripts/after-shipit-pod-push.js
Labels: patch

#129 Publish to Maven Central before the docs
  scripts/release.sh
Labels: minor

#117 Expose utils for expression LSP
  core/player/src/expressions/__tests__/parser.test.ts
  core/player/src/expressions/__tests__/utils.test.ts
  core/player/src/expressions/evaluator.ts
  core/player/src/expressions/index.ts
  core/player/src/expressions/parser.ts
  core/player/src/expressions/types.ts
Labels: minor

#130 Parse and Forward Symbols in the View Parser
  core/player/src/view/parser/__tests__/parser.test.ts
  core/player/src/view/parser/index.ts
Labels: patch

#134 Increase Maven Central timeouts to 10 min
  scripts/release.sh
Labels: patch

#131 sync up to latest
  core/make-flow/src/index.ts
  core/player/src/__tests__/validation.test.ts
  core/player/src/controllers/data.ts
  core/player/src/player.ts
  core/player/src/plugins/default-exp-plugin.ts
  core/player/src/schema/__tests__/schema.test.ts
  core/player/src/schema/schema.ts
  core/player/src/string-resolver/index.ts
  core/player/src/validator/validation-middleware.ts
  core/types/src/index.ts
  plugins/auto-scroll/react/src/__tests__/plugin.test.tsx
  plugins/auto-scroll/react/src/plugin.tsx
  plugins/data-change-listener/core/BUILD
  plugins/data-change-listener/core/src/index.test.ts
  plugins/data-change-listener/core/src/index.ts
Labels: minor, skip-release
