Repository player-ui/player, pull requests merged in 2024-11, with the labels that each got.

#538 Minor Docs Fixes
  docs/site/astro.config.mjs
  docs/site/src/content/docs/index.mdx
  scripts/release.sh
  scripts/workspace-status.sh
Labels: documentation, skip-release

#533 Fix parsing of Bindings with Escaped Numbers
  core/player/src/binding-grammar/custom/index.ts
  core/player/src/binding/__tests__/parser.bench.ts
  core/player/src/binding/__tests__/resolver.test.ts
  package.json
  plugins/reference-assets/components/BUILD
  pnpm-lock.yaml
  vitest.config.ts
Labels: patch

#547 Remove unneeded dependency on `pubsub-js`
  package.json
  plugins/pubsub/core/BUILD
  pnpm-lock.yaml
Labels: skip-release

#544 Applicability docs
  BUILD.bazel
  docs/site/src/content/docs/content/assets-views.mdx
  plugins/reference-assets/react/src/__tests__/integration.test.tsx
  react/player/src/__tests__/__snapshots__/app.test.tsx.snap
  tools/BUILD
  tools/defs.bzl
  tools/vitest.config.mts.tmpl
  vitest.config.mts
Labels: patch

#546 improve prominence of bazel build guidance for iOS targets
  ios/README.md
Labels: documentation

#548 Add Missing DSL Docs
  .github/PULL_REQUEST_TEMPLATE.md
  docs/site/astro.config.mjs
  docs/site/src/content/docs/authoring/index.mdx
  docs/site/src/content/docs/authoring/plugins.mdx
  docs/site/src/content/docs/authoring/schema.mdx
  docs/site/src/content/docs/authoring/views.mdx
Labels: documentation

#552 JVM ConsoleLoggerPlugin
  MODULE.bazel
  jvm/hermes/deps.bzl
  jvm/hermes/src/main/kotlin/com/intuit/playerui/hermes/bridge/runtime/HermesRuntime.kt
  plugins/console-logger/jvm/BUILD.bazel
  plugins/console-logger/jvm/deps.bzl
  plugins/console-logger/jvm/src/main/kotlin/com/intuit/playerui/plugins/consolelogger/ConsoleLoggerPlugin.kt
  plugins/console-logger/jvm/src/test/kotlin/com/intuit/playerui/plugins/consolelogger/ConsoleLoggerPluginTest.kt
Labels: patch
