Repository player-ui/player, pull requests merged in 2024-01, with the labels that each got.

#266 DSL documentation changes
  docs/site/pages/content/dsl.mdx
Labels: documentation, skip-release

#263 Latest sync including AsyncNodePlugin
  android/demo/scripts/androidtest.sh
  android/demo/src/androidTest/java/com/intuit/player/android/reference/demo/test/fragment/PlayerFragmentScrollingTest.kt
  core/player/src/controllers/flow/__tests__/flow.test.ts
  core/player/src/controllers/flow/flow.ts
  core/player/src/view/parser/index.ts
  core/player/src/view/parser/types.ts
  core/player/src/view/parser/utils.ts
  core/player/src/view/plugins/switch.ts
  core/player/src/view/resolver/index.ts
  core/player/src/view/resolver/utils.ts
  core/player/src/view/view.ts
  ios/packages/core/Sources/Types/Core/Flow.swift
  ios/packages/test-utils/ViewInspector/ui-test/AssetFlowViewTests.swift
  ios/plugins/StageRevertDataPlugin/Tests/StageRevertDataPluginTests.swift
  package.json
  plugins/async-node/core/BUILD
  plugins/async-node/core/src/index.test.ts
  plugins/async-node/core/src/index.ts
  plugins/async-node/core/src/types.ts
  plugins/reference-assets/mocks/action/action-basic.tsx
  plugins/reference-assets/mocks/action/action-transition-to-end.tsx
  scripts/yarn-link-setup.js
  tools/storybook/src/addons/events/events.css
  tools/storybook/src/addons/events/index.tsx
  xcode/Podfile.lock
  yarn.lock
Labels: minor

#276 Fix SwiftUIPendingTransactionPlugin Docs Page
  docs/site/pages/plugins/swiftui-pending-transaction.mdx
Labels: documentation, skip-release

#277 Remove Applitools
  .circleci/config.yml
  PlayerUI.podspec
  WORKSPACE
  android/build.bzl
  android/demo/BUILD
  android/demo/androidsettings.xml
  android/demo/deps.bzl
  android/demo/src/androidTest/java/com/intuit/player/android/reference/demo/test/SplashActivityTest.kt
  android/demo/src/androidTest/java/com/intuit/player/android/reference/demo/test/assets/action/ActionUITest.kt
  android/demo/src/androidTest/java/com/intuit/player/android/reference/demo/test/assets/info/InfoUITest.kt
  android/demo/src/androidTest/java/com/intuit/player/android/reference/demo/test/assets/input/InputUITest.kt
  android/demo/src/androidTest/java/com/intuit/player/android/reference/demo/test/base/ApplitoolsTest.kt
  android/demo/src/androidTest/java/com/intuit/player/android/reference/demo/test/base/AssetUITest.kt
  android/player/src/main/java/com/intuit/player/android/asset/SuspendableAsset.kt
  generated.bzl
  ios/packages/reference-assets/UITests/ActionAssetUITests.swift
  ios/packages/reference-assets/UITests/BaseTestCase.swift
  ios/packages/reference-assets/UITests/BeaconPluginUITest.swift
  ios/packages/reference-assets/UITests/CollectionAssetUITests.swift
  ios/packages/reference-assets/UITests/ExternalActionUITests.swift
  ios/packages/reference-assets/UITests/InfoAssetUITests.swift
  ios/packages/reference-assets/UITests/InputAssetUITests.swift
  ios/packages/reference-assets/UITests/ManagedPlayerUITests.swift
  ios/packages/reference-assets/UITests/PubsubUITests.swift
  ios/packages/reference-assets/UITests/SwiftUIPendingTransactionPluginUITests.swift
  ios/packages/reference-assets/UITests/TextAssetUITests.swift
  jvm/dependencies/versions.bzl
  jvm/utils/src/main/kotlin/com/intuit/player/jvm/utils/mocks/ClassLoaderMocksReader.kt
  xcode/PlayerUI.xcodeproj/project.pbxproj
  xcode/Podfile
  xcode/Podfile.lock
Labels: patch, tests

#275 [JVM] pom with minimal oss requirements
  jvm/BUILD
  jvm/build.bzl
  jvm/pom.tpl
Labels: documentation, skip-release

#278 feat: add github.dev links to docs
  docs/site/next.config.mjs
  docs/site/plugins/mdx-link-append-loader.js
Labels: minor, skip-release

#279 iOS: Update Writing Plugins guide
  docs/site/pages/assets/custom.mdx
  docs/site/pages/getting-started.mdx
  docs/site/pages/writing-plugins.mdx
Labels: documentation, skip-release

#280 Update Team Page with New Members
  docs/site/components/PlayerTeam.tsx
  docs/site/config/team.json
Labels: documentation, skip-release

#284 iOS: Update plugin documentation
  docs/site/pages/plugins/beacon.mdx
  docs/site/pages/plugins/check-path.mdx
  docs/site/pages/plugins/common-expressions.mdx
  docs/site/pages/plugins/common-types.mdx
  docs/site/pages/plugins/computed-properties.mdx
  docs/site/pages/plugins/console-logger.mdx
  docs/site/pages/plugins/expression.mdx
  docs/site/pages/plugins/external-action-view-modifier.mdx
  docs/site/pages/plugins/external-action.mdx
  docs/site/pages/plugins/metrics.mdx
  docs/site/pages/plugins/partial-match-fingerprint.mdx
  docs/site/pages/plugins/pub-sub.mdx
  docs/site/pages/plugins/stage-revert-data.mdx
  docs/site/pages/plugins/swiftui-pending-transaction.mdx
  docs/site/pages/plugins/transition.mdx
  docs/site/pages/plugins/types-provider.mdx
Labels: documentation, skip-release

#282 docDays/updated FAQS
  docs/site/pages/faqs.mdx
Labels: documentation, skip-release
