Repository player-ui/player, pull requests merged in 2024-03, with the labels that each got.

#296 [Android] `AsyncHydrationTrackerPlugin`
  android/demo/src/main/java/com/intuit/playerui/android/reference/demo/lifecycle/DemoPlayerViewModel.kt
  android/player/src/main/java/com/intuit/playerui/android/asset/SuspendableAsset.kt
  android/player/src/test/java/com/intuit/playerui/android/renderer/NestedAssetTest.kt
  plugins/beacon/jvm/src/main/kotlin/com/intuit/playerui/plugins/beacon/BeaconPlugin.kt
Labels: patch

#310 iOS: prefix resource bundles to prevent naming collisions
  PlayerUI.podspec
  generated.bzl
  ios/packages/reference-assets/Sources/ReferenceAssetsPlugin.swift
  ios/packages/test-utils-core/Sources/AssetTestHelper.swift
  ios/plugins/AsyncNodePlugin/Sources/AsyncNodePlugin.swift
  ios/plugins/BaseBeaconPlugin/Sources/BaseBeaconPlugin.swift
  ios/plugins/CheckPathPlugin/Sources/CheckPathPlugin.swift
  ios/plugins/CommonExpressionsPlugin/Sources/CommonExpressionsPlugin.swift
  ios/plugins/CommonTypesPlugin/Sources/CommonTypesPlugin.swift
  ios/plugins/ComputedPropertiesPlugin/Sources/ComputedPropertiesPlugin.swift
  ios/plugins/ExpressionPlugin/Sources/ExpressionPlugin.swift
  ios/plugins/ExternalActionPlugin/Sources/ExternalActionPlugin.swift
  ios/plugins/ExternalActionViewModifierPlugin/Sources/ExternalActionViewModifierPlugin.swift
  ios/plugins/MetricsPlugin/Sources/MetricsPlugin.swift
  ios/plugins/PubSubPlugin/Sources/PubSubPlugin.swift
  ios/plugins/StageRevertDataPlugin/Sources/StageRevertDataPlugin.swift
  ios/plugins/TypesProviderPlugin/Sources/TypesProviderPlugin.swift
  xcode/Podfile
  xcode/Podfile.lock
Labels: patch

#302 Common Types Plugin restoring old dataRefs
  plugins/common-types/core/src/data-types/refs.ts
  plugins/common-types/core/src/data-types/types.ts
  plugins/common-types/core/src/index.ts
  plugins/reference-assets/components/BUILD
  plugins/reference-assets/components/src/index.tsx
Labels: patch

#315 Expression Parser Strictness
  core/player/src/expressions/evaluator.ts
  core/player/src/expressions/parser.ts
Labels: patch

#317 add syntax examples for default expressions
  docs/site/pages/content/data-expressions.mdx
Labels: documentation

#319 Fix `commaNumber` Formatting when Using a Precision of 0
  plugins/common-types/core/src/formats/__tests__/formats.test.ts
  plugins/common-types/core/src/formats/index.ts
Labels: patch

#309 PR Checklist update
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation, skip-release

#323 update iOS contributing guide
  CONTRIBUTING.md
  tools/build_ios_bundles.sh
Labels: skip-release

#321 refactor nav docs slightly to better call out onEnd expressions
  docs/site/pages/content/navigation.mdx
Labels: documentation, skip-release
