Repository player-ui/player, pull requests merged in 2024-07, with the labels that each got.

#390 iOS: use updated ios pipeline macro with uitest target
  plugins/reference-assets/swiftui/BUILD.bazel
  tools/ios/util.bzl
Labels: patch, Bazel 6

#427 Fix NPM Registry URL
  .circleci/config.yml
Labels: skip-release

#426 [JVM] Publish next releases to release repository
  .autorc
  package.json
Labels: internal

#429 Revert "[JVM] Publish next releases to release repository"
  .autorc
  package.json
Labels: internal

#433 Update CONTRIBUTING.md
  .circleci/config.yml
  CONTRIBUTING.md
Labels: documentation

#435 Bazel clean up
  .circleci/config.yml
  MODULE.bazel
  WORKSPACE.bzlmod
  android/demo/BUILD
  android/demo/deps.bzl
  android/demo/src/androidTest/java/com/intuit/playerui/android/reference/demo/test/assets/action/ActionUITest.kt
  android/demo/src/androidTest/java/com/intuit/playerui/android/reference/demo/test/assets/collection/CollectionUITest.kt
  android/demo/src/androidTest/java/com/intuit/playerui/android/reference/demo/test/assets/info/InfoUITest.kt
  android/demo/src/androidTest/java/com/intuit/playerui/android/reference/demo/test/assets/input/InputUITest.kt
  android/demo/src/androidTest/java/com/intuit/playerui/android/reference/demo/test/assets/text/TextUITest.kt
  android/demo/src/androidTest/java/com/intuit/playerui/android/reference/demo/test/base/AssetUITest.kt
  android/player/BUILD
  android/player/deps.bzl
  android/player/src/main/java/com/intuit/playerui/android/asset/SuspendableAsset.kt
  android/player/src/main/java/com/intuit/playerui/android/ui/FallbackBinding.kt
  android/player/src/main/java/com/intuit/playerui/android/ui/PlayerBinding.kt
  android/player/src/main/java/com/intuit/playerui/android/ui/PlayerFragment.kt
  android/player/src/main/res/layout/fallback_view.xml
  android/player/src/main/res/layout/player_fragment.xml
  docs/BUILD
  jvm/core/src/main/kotlin/com/intuit/playerui/core/plugins/JSScriptPluginWrapper.kt
  plugins/beacon/jvm/src/main/kotlin/com/intuit/playerui/plugins/beacon/BeaconPlugin.kt
  plugins/expression/jvm/src/main/kotlin/com/intuit/playerui/plugins/expression/ExpressionPlugin.kt
  plugins/external-action/jvm/src/main/kotlin/com/intuit/playerui/plugins/externalAction/ExternalActionPlugin.kt
  plugins/metrics/jvm/src/main/kotlin/com/intuit/playerui/plugins/metrics/MetricsPlugin.kt
  plugins/pubsub/jvm/src/main/kotlin/com/intuit/playerui/plugins/pubsub/PubSubPlugin.kt
  plugins/reference-assets/android/BUILD
  plugins/reference-assets/android/defs.bzl
  plugins/reference-assets/android/deps.bzl
  plugins/reference-assets/android/src/androidTest/java/com/intuit/playerui/android/reference/assets/action/ActionTest.kt
  plugins/reference-assets/android/src/androidTest/java/com/intuit/playerui/android/reference/assets/collection/CollectionTest.kt
  plugins/reference-assets/android/src/androidTest/java/com/intuit/playerui/android/reference/assets/info/InfoTest.kt
  plugins/reference-assets/android/src/androidTest/java/com/intuit/playerui/android/reference/assets/input/InputTest.kt
  plugins/reference-assets/android/src/androidTest/java/com/intuit/playerui/android/reference/assets/test/AssetTest.kt
  plugins/reference-assets/android/src/androidTest/java/com/intuit/playerui/android/reference/assets/test/BUILD
  plugins/reference-assets/android/src/androidTest/java/com/intuit/playerui/android/reference/assets/test/deps.bzl
  plugins/reference-assets/android/src/androidTest/java/com/intuit/playerui/android/reference/assets/text/TextTest.kt
  scripts/release.sh
Labels: patch

#432 Remove alternate binding parsers from bundle
  core/player/BUILD
  core/player/src/binding-grammar/__tests__/ebnf/binding.ebnf
  core/player/src/binding-grammar/__tests__/ebnf/index.ts
  core/player/src/binding-grammar/__tests__/ebnf/types.ts
  core/player/src/binding-grammar/__tests__/parser.test.ts
  core/player/src/binding-grammar/__tests__/parsimmon/index.ts
  core/player/src/binding-grammar/index.ts
  core/player/src/binding/__tests__/resolver.test.ts
Labels: internal

#440 apply strategy from pr builds to main & release builds
  .circleci/config.yml
Labels: skip-release

#445 Specific Temurin Version
  .circleci/config.yml
Labels: skip-release

#442 JS Package Cleanup
  .bazelignore
  docs/storybook/.storybook/main.ts
  docs/storybook/.storybook/preview.js
  docs/storybook/BUILD
  docs/storybook/package.json
  docs/storybook/src/ManagedPlayer.stories.tsx
  docs/storybook/src/Player.stories.tsx
  docs/storybook/src/reference-assets/Action.stories.tsx
  docs/storybook/src/reference-assets/Choice.stories.tsx
  docs/storybook/src/reference-assets/Collection.stories.tsx
  docs/storybook/src/reference-assets/Image.stories.tsx
  docs/storybook/src/reference-assets/Info.stories.tsx
  docs/storybook/src/reference-assets/Input.stories.tsx
  docs/storybook/src/reference-assets/Text.stories.tsx
  package.json
  plugins/pubsub/core/package.json
  pnpm-lock.yaml
  tools/storybook/BUILD
  tools/storybook/manager.mjs
  tools/storybook/package.json
  tools/storybook/preview.mjs
  tools/storybook/src/addons/appetize/index.tsx
  tools/storybook/src/addons/constants.ts
  tools/storybook/src/addons/editor/index.tsx
  tools/storybook/src/addons/events/events.css
  tools/storybook/src/addons/events/index.tsx
  tools/storybook/src/addons/refresh/index.tsx
  tools/storybook/src/addons/useDarkMode.ts
  tools/storybook/src/decorator/index.tsx
  tools/storybook/src/dsl/createDSLStory.tsx
  tools/storybook/src/dsl/index.ts
  tools/storybook/src/dsl/transpile.ts
  tools/storybook/src/index.ts
  tools/storybook/src/manager.tsx
  tools/storybook/src/player/Appetize.tsx
  tools/storybook/src/player/PlayerFlowSummary.tsx
  tools/storybook/src/player/PlayerStory.tsx
  tools/storybook/src/player/index.ts
  tools/storybook/src/player/storybookReactPlayerPlugin.ts
  tools/storybook/src/player/useFlowSet.tsx
  tools/storybook/src/preview.tsx
  tools/storybook/src/redux/index.tsx
  tools/storybook/src/state/events.ts
  tools/storybook/src/state/index.ts
  tools/storybook/src/types.ts
  tools/storybook/tsconfig.json
  tools/storybook/tsup.config.ts
Labels: patch

#404 Ability to remove a resolved async node
  docs/site/pages/plugins/async-node.mdx
  plugins/async-node/core/src/index.test.ts
  plugins/async-node/core/src/index.ts
Labels: patch

#430 bump js rules, use node 20
  MODULE.bazel
  package.json
Labels: skip-release, dependencies

#431 Update to use TypeScript 5.5 and enable `isolatedDeclarations`
  package.json
  pnpm-lock.yaml
  tsconfig.json
Labels: skip-release, dependencies

#454 Log debug info for npm next release
  scripts/release.sh
Labels: internal

#456 Use smaller docker image for circle setup
  .circleci/config.yml
Labels: internal

#443 Fix J2V8 Debugger
  .circleci/config.yml
  WORKSPACE.bzlmod
  android/demo/deps.bzl
  android/demo/src/main/java/com/intuit/playerui/android/reference/demo/lifecycle/DemoPlayerViewModel.kt
  android/demo/src/main/java/com/intuit/playerui/android/reference/demo/ui/base/BasePlayerFragment.kt
  android/player/BUILD
  android/player/deps.bzl
  android/player/src/main/java/com/intuit/playerui/android/AndroidPlayer.kt
  android/player/src/main/java/com/intuit/playerui/android/debug/UnsupportedScriptProvider.kt
  jvm/core/BUILD
  jvm/j2v8/BUILD
  jvm/j2v8/defs.bzl
Labels: patch
