Repository player-ui/player, pull requests merged in 2024-08, with the labels that each got.

#472 Update to rules player 1.1.1
  MODULE.bazel
Labels: patch

#473 Update rules1.1.2
  MODULE.bazel
Labels: patch

#474 Docs and Release Fixes
  .autorc
  docs/site/components/App.tsx
  docs/site/config/navigation.ts
  docs/site/package.json
  scripts/release.sh
Labels: patch

#475 Docsite Fixes
  BUILD.bazel
  MODULE.bazel
  docs/BUILD
  docs/site/components/Image.tsx
  docs/site/components/Navigation.tsx
  docs/site/config/constants.ts
  docs/site/next.config.mjs
  docs/site/webpack.config.ts
Labels: patch

#449 Storybook Addon Fixes
  MODULE.bazel
  docs/site/pages/tools/storybook.mdx
  docs/site/public/tools/storybook/docs-addon.gif
  docs/storybook/.storybook/main.ts
  docs/storybook/.storybook/preview.js
  docs/storybook/BUILD
  docs/storybook/package.json
  docs/storybook/src/Welcome.mdx
  docs/storybook/src/reference-assets/Action.stories.tsx
  docs/storybook/src/reference-assets/Choice.stories.tsx
  docs/storybook/src/reference-assets/Collection.stories.tsx
  docs/storybook/src/reference-assets/Image.stories.tsx
  docs/storybook/src/reference-assets/Info.stories.tsx
  docs/storybook/src/reference-assets/Input.stories.tsx
  docs/storybook/src/reference-assets/Text.stories.tsx
  package.json
  pnpm-lock.yaml
  tools/storybook/BUILD
  tools/storybook/package.json
  tools/storybook/src/addons/constants.ts
  tools/storybook/src/addons/docs/index.tsx
  tools/storybook/src/addons/docs/ts-convert.ts
  tools/storybook/src/addons/editor/index.tsx
  tools/storybook/src/addons/events/events.css
  tools/storybook/src/addons/events/index.tsx
  tools/storybook/src/addons/refresh/index.tsx
  tools/storybook/src/addons/useDarkMode.ts
  tools/storybook/src/manager.tsx
  tools/storybook/src/redux/index.tsx
Labels: minor

#482 [CI] Swap release script to use `config=ci`
  scripts/release.sh
Labels: skip-release

#471 On update race condition
  .circleci/config.yml
  android/player/src/main/java/com/intuit/playerui/android/ui/PlayerFragment.kt
  jvm/core/src/main/kotlin/com/intuit/playerui/core/view/View.kt
Labels: patch

#490 fix:no matching toolchains:ninja_toolchain
  .bazelrc
  .circleci/config.yml
  MODULE.bazel
Labels: skip-release

#468 Add recipes for just
  CONTRIBUTING.md
  justfile
  package.json
  scripts/mvn-install.sh
  scripts/pkg-roots.sh
  scripts/yarn-link-setup.js
Labels: skip-release, internal

#496 Update Rules Versions
  BUILD.bazel
  MODULE.bazel
  package.json
  plugins/reference-assets/react/src/__tests__/integration.test.tsx
  pnpm-lock.yaml
Labels: skip-release
