Repository player-ui/player, pull requests merged in 2024-04, with the labels that each got.

#328 Expose More Information About Expression Parsing Errors
  core/player/src/expressions/parser.ts
  core/player/src/expressions/types.ts
  core/player/src/expressions/utils.ts
Labels: patch

#262 iOS: Bazel 6 build updates
  .bazelignore
  .bazelrc
  .circleci/config.yml
  .gitignore
  BUILD.bazel
  CONTRIBUTING.md
  MODULE.bazel
  ios/BUILD.bazel
  ios/core/Tests/Types/Generic/AnyTypeTests.swift
  ios/core/Tests/utilities/ErrorUtilitiesTests.swift
  ios/swiftui/Tests/ManagedPlayer/ManagedPlayerViewModelTests.swift
  ios/swiftui/Tests/SwiftUIRegistryTests.swift
  ios/swiftui/ViewInspector/ManagedPlayer/ManagedPlayerTests.swift
  ios/swiftui/ViewInspector/SwiftUIPlayerTests.swift
  ios/test-utils/BUILD.bazel
  ios/test-utils/ViewInspector/ui-test/AssetFlowViewTests.swift
  ios/test-utils/ViewInspector/unit-test/SwiftUIAssetUnitTestCaseTests.swift
  plugins/beacon/swiftui/ViewInspector/BeaconPluginTests.swift
  plugins/check-path/ios/BUILD.bazel
  plugins/check-path/swiftui/ViewInspector/SwiftUICheckPathPluginTests.swift
  plugins/external-action/ios/Tests/ExternalActionPluginTests.swift
  plugins/external-action/swiftui/ViewInspector/ExternalActionViewModifierPluginTests.swift
  plugins/pending-transaction/swiftui/ViewInspector/SwiftUIPendingTransactionPlugin.swift
  plugins/reference-assets/swiftui/BUILD.bazel
  plugins/reference-assets/swiftui/Resources/BUILD.bazel
  plugins/reference-assets/swiftui/Sources/SwiftUI/InputAsset.swift
  plugins/reference-assets/swiftui/Sources/Utilities/InternalAssets.swift
  plugins/reference-assets/swiftui/UITests/ActionAssetUITests.swift
  plugins/reference-assets/swiftui/UITests/BaseTestCase.swift
  plugins/reference-assets/swiftui/UITests/CollectionAssetUITests.swift
  plugins/reference-assets/swiftui/UITests/InfoAssetUITests.swift
  plugins/reference-assets/swiftui/UITests/InputAssetUITests.swift
  plugins/reference-assets/swiftui/UITests/TextAssetUITests.swift
  plugins/reference-assets/swiftui/ViewInspector/SwiftUI/ActionAssetTests.swift
  plugins/reference-assets/swiftui/ViewInspector/SwiftUI/CollectionAssetTests.swift
  plugins/reference-assets/swiftui/ViewInspector/SwiftUI/InfoAssetTests.swift
  plugins/reference-assets/swiftui/ViewInspector/SwiftUI/InputAssetTests.swift
  plugins/reference-assets/swiftui/ViewInspector/SwiftUI/TextAssetTests.swift
  swift_deps.bzl
  swift_deps_index.json
  tools/ios/BUILD.bazel
  tools/ios/Info.plist
  xcode/Package.resolved
  xcode/Package.swift
Labels: Bazel 6

#314 Android: Preserve old rendering path for non-suspendable assets
  WORKSPACE
  android/player/api/player.api
  android/player/src/main/java/com/intuit/playerui/android/ui/PlayerFragment.kt
  android/player/src/main/res/layout/fallback_view.xml
  android/player/src/main/res/layout/player_fragment.xml
  jvm/core/src/main/kotlin/com/intuit/playerui/core/player/HeadlessPlayer.kt
Labels: patch

#326 [Docs] Update the DSL Benefits in Schema Section
  docs/site/pages/dsl/schema.mdx
Labels: documentation, skip-release

#330 Version Selector Fixes
  docs/site/components/Navigation.tsx
Labels: patch

#334 Update Player Tools Version
  package.json
  yarn.lock
Labels: patch

#339 [Docs] DSL docs additions
  docs/site/pages/dsl/index.mdx
  docs/site/pages/dsl/schema.mdx
  docs/site/pages/dsl/views.mdx
Labels: documentation

#344 Add bazelisk to list of requirements; be more specific in Android build instructions
  CONTRIBUTING.md
  android/demo/README.md
Labels: documentation

#343 [Android] Reorganize `PlayerFragment` state updates
  android/demo/src/main/java/com/intuit/playerui/android/reference/demo/ui/base/BasePlayerFragment.kt
  android/player/src/main/java/com/intuit/playerui/android/extensions/Into.kt
  android/player/src/main/java/com/intuit/playerui/android/ui/PlayerFragment.kt
  scripts/mvn-install.sh
Labels: patch

#347 Parse multi node switch fixv1
  .npmrc
  core/player/src/view/__tests__/view.test.ts
  core/player/src/view/parser/index.ts
  core/player/src/view/plugins/switch.ts
Labels: patch

#352 Trigger prerelease
  jvm/core/src/main/kotlin/com/intuit/playerui/core/player/HeadlessPlayer.kt
Labels: patch
