Repository player-ui/player, pull requests merged in 2024-09, with the labels that each got.

#503 [skip ci] Update CircleCI Config to use Bazelrc During next/release Builds
  .circleci/config.yml
Labels: skip-release, internal

#348 Update Custom Asset doc page with use cases on asset registering
  docs/site/pages/assets/custom.mdx
Labels: patch, skip-release

#505 [skip ci] Fix Android Config Setup During Bazelrc Setup Phase During Build
  .circleci/config.yml
Labels: skip-release, internal

#507 Fix js Package Releases
  scripts/release.sh
Labels: patch

#512 revert async node flatten
  core/player/src/view/resolver/index.ts
  plugins/async-node/core/src/index.test.ts
  plugins/async-node/ios/Tests/AsynNodePluginTests.swift
  plugins/async-node/jvm/src/test/kotlin/com/intuit/playerui/plugins/asyncnode/AsyncNodePluginTest.kt
Labels: patch

#516 Remove FBJNI local binaries
  WORKSPACE.bzlmod
  jvm/hermes/BUILD
  jvm/hermes/libs/BUILD
  jvm/hermes/libs/arm64-v8a/BUILD
  jvm/hermes/libs/arm64-v8a/libc++_shared.so
  jvm/hermes/libs/arm64-v8a/libfbjni.so
  jvm/hermes/libs/armeabi-v7a/BUILD
  jvm/hermes/libs/armeabi-v7a/libc++_shared.so
  jvm/hermes/libs/armeabi-v7a/libfbjni.so
  jvm/hermes/libs/x86/BUILD
  jvm/hermes/libs/x86/libc++_shared.so
  jvm/hermes/libs/x86/libfbjni.so
  jvm/hermes/libs/x86_64/BUILD
  jvm/hermes/libs/x86_64/libc++_shared.so
  jvm/hermes/libs/x86_64/libfbjni.so
  third_party/fbjni/artifact.BUILD
Labels: patch

#517 hermes_jni linkopt select
  jvm/hermes/src/main/jni/BUILD
Labels: skip-release
