Repository player-ui/player, pull requests merged in 2024-10, with the labels that each got.

#519 iOS: Expand AnyType to handle deeply nested AnyType for beacon encoding
  ios/core/Sources/Types/Assets/BaseAssetRegistry.swift
  ios/core/Sources/Types/Generic/AnyType.swift
  ios/core/Tests/Types/Generic/AnyTypeTests.swift
Labels: patch

#525 Fix CJS support for React Player
  package.json
  pnpm-lock.yaml
Labels: patch

#480 Fix circleci badge in README
  README.md
Labels: documentation, skip-release, internal

#524 ios: enhance tapable logger to handle variadic args from the JS log
  ios/core/Sources/Player/HeadlessPlayer.swift
  ios/core/Tests/utilities/JSLoggerTests.swift
  ios/logger/Sources/TapableLogger.swift
  ios/logger/Tests/TapableLoggerTests.swift
  ios/swiftui/Tests/SwiftUIRegistryTests.swift
  plugins/console-logger/ios/Sources/PrintLoggerPlugin.swift
  plugins/console-logger/ios/Tests/PrintLoggerPluginTests.swift
Labels: minor

#532 More Doc Fixes
  docs/site/BUILD
  docs/site/astro.config.mjs
  docs/site/src/components/tools/VersionSelector.tsx
  docs/site/src/content/docs/guides/getting-started.mdx
  docs/site/src/content/docs/index.mdx
  docs/site/src/content/docs/plugins/core/common-expressions.mdx
  docs/site/src/content/docs/plugins/core/common-types.mdx
  docs/site/src/content/docs/plugins/multiplatform/asset-provider.mdx
  docs/site/src/content/docs/plugins/multiplatform/check-path.mdx
  docs/site/src/content/docs/plugins/multiplatform/external-action.mdx
  docs/site/src/content/docs/tools/storybook.mdx
  docs/site/src/content/docs/xlr/usage.mdx
  package.json
  pnpm-lock.yaml
Labels: patch

#511 fix exports in docs
  docs/site/src/content/docs/plugins/core/common-expressions.mdx
  docs/site/src/content/docs/plugins/core/common-types.mdx
  docs/site/src/content/docs/plugins/multiplatform/check-path.mdx
Labels: documentation
