Repository player-ui/player, pull requests merged in 2025-05, with the labels that each got.

#638 Use Readonly Key for Forked Builds
  .circleci/config.yml
Labels: skip-release

#643 Fix name of forked bazelrc job
  .circleci/config.yml
Labels: skip-release

#645 Fully disable cache for forked builds
  .circleci/config.yml
Labels: skip-release

#646 Pull in PRs 636 and 637
  core/player/src/player.ts
  docs/site/astro.config.mjs
  react/player/src/player.tsx
  tsup.config.ts
Labels: patch

#648 Revert "Merge pull request #646 from player-ui/ops/merge-636-and-637"
  core/player/src/player.ts
  docs/site/astro.config.mjs
  react/player/src/player.tsx
  tsup.config.ts
Labels: patch

#621 fix: CheckPathPlugin throws error with chained AsyncNode
  core/player/src/view/resolver/index.ts
  core/player/src/view/resolver/utils.ts
  plugins/async-node/core/BUILD
  plugins/async-node/core/package.json
  plugins/async-node/core/src/__tests__/index.test.ts
  pnpm-lock.yaml
Labels: bug

#659 remove new line at end of VERSION file
  VERSION
Labels: skip-release

#630 Renew hydration scope, wrap composableAsset and apply the modifiers to all assets through the compose call
  android/player/src/main/java/com/intuit/playerui/android/AndroidPlayer.kt
  android/player/src/main/java/com/intuit/playerui/android/compose/ComposableAsset.kt
  docs/site/src/content/docs/assets/custom.mdx
  plugins/reference-assets/android/src/main/java/com/intuit/playerui/android/reference/assets/action/Action.kt
  plugins/reference-assets/android/src/main/java/com/intuit/playerui/android/reference/assets/badge/Badge.kt
  plugins/reference-assets/android/src/main/java/com/intuit/playerui/android/reference/assets/collection/Collection.kt
Labels: minor
