Repository player-ui/player, pull requests merged in 2025-01, with the labels that each got.

#567 Updated Authoring content section in docs.mdx
  docs/site/src/content/docs/authoring/plugins.mdx
Labels: documentation, skip-release

#563 Hermes reference tracking
  jvm/hermes/src/main/jni/BUILD
  jvm/hermes/src/main/jni/JHermesRuntime.h
  jvm/hermes/src/main/jni/JJSIValue.cpp
  jvm/hermes/src/main/jni/JJSIValue.h
  jvm/hermes/src/main/jni/RuntimeScope.cpp
  jvm/hermes/src/main/jni/RuntimeScope.h
  jvm/hermes/src/main/kotlin/com/intuit/playerui/jsi/Value.kt
  jvm/perf/src/main/kotlin/com/intuit/playerui/perf/jmh/PlayerPerf.kt
Labels: patch

#565 Fix Binding Instantiation of Escaped Numerical Bindings
  CHANGELOG.md
  core/player/src/binding/__tests__/binding.test.ts
  core/player/src/binding/__tests__/parser.bench.ts
  core/player/src/binding/binding.ts
  package.json
  pnpm-lock.yaml
  scripts/next-changelogs.js
Labels: patch

#569 Fix Duplicate Date in Title for `next` Changelog Entries
  CHANGELOG.md
  scripts/next-changelogs.js
Labels: documentation, skip-release

#566 Only mutate ManagedPlayerViewModel.loadingState on main thread
  ios/swiftui/Sources/ManagedPlayer/ManagedPlayerViewModel.swift
  ios/swiftui/Tests/ManagedPlayer/ManagedPlayerViewModelTests.swift
Labels: patch

#576 J2V8 Config from Consumer
  jvm/core/src/main/kotlin/com/intuit/playerui/core/player/HeadlessPlayer.kt
  jvm/j2v8/src/main/kotlin/com/intuit/playerui/j2v8/bridge/runtime/V8Runtime.kt
Labels: patch

#573 Broken links fix for docs
  docs/site/src/content/docs/authoring/index.mdx
Labels: skip-release

#578 Check scope active for awaiting player
  android/player/src/main/java/com/intuit/playerui/android/lifecycle/PlayerViewModel.kt
  android/player/src/test/java/com/intuit/playerui/android/lifecycle/PlayerViewModelTest.kt
Labels: patch

#580 Hermes tracker update
  jvm/hermes/src/main/jni/JHermesRuntime.h
  jvm/hermes/src/main/jni/JJSIValue.h
  jvm/hermes/src/main/jni/RuntimeScope.cpp
  jvm/hermes/src/main/jni/RuntimeScope.h
Labels: patch
