Repository player-ui/player, pull requests merged in 2025-04, with the labels that each got.

#632 Hermes Build Fixes and Upgrade, Better Cache Uses, and ESLint v9 Upgrade
  .bazelrc
  .circleci/config.yml
  .eslintrc.js
  BUILD.bazel
  WORKSPACE.bzlmod
  core/partial-match-registry/src/deep-partial-matcher.ts
  core/player/src/__tests__/validation.test.ts
  core/player/src/binding/__tests__/parser.bench.ts
  core/player/src/controllers/flow/__tests__/flow.test.ts
  core/player/src/expressions/utils.ts
  core/player/src/player.ts
  core/player/src/view/builder/index.ts
  core/player/src/view/resolver/__tests__/edgecases.test.ts
  core/player/src/view/resolver/types.ts
  docs/site/src/content/docs/plugins/core/common-expressions.mdx
  eslint.config.mts
  jvm/hermes/README.md
  jvm/hermes/src/main/jni/JHermesRuntime.h
  jvm/hermes/src/main/kotlin/com/intuit/playerui/hermes/bridge/runtime/HermesRuntime.kt
  package.json
  plugins/async-node/core/src/__tests__/index.test.ts
  plugins/async-node/core/src/transform.ts
  plugins/common-types/core/src/formats/__tests__/formats.test.ts
  plugins/common-types/core/src/validators/index.ts
  plugins/data-change-listener/core/src/index.ts
  plugins/pubsub/core/src/__tests__/pubsub.test.ts
  plugins/reference-assets/react/postcss.config.js
  plugins/reference-assets/react/src/components/Input.tsx
  plugins/reference-assets/react/src/plugin.tsx
  plugins/reference-assets/react/tailwind.config.js
  pnpm-lock.yaml
  scripts/release.sh
  third_party/fbjni/BUILD
  third_party/hermes/BUILD
  third_party/rn/arm64-v8a/libhermes.so
  third_party/rn/arm64-v8a/libjsi.so
  third_party/rn/armeabi-v7a/libhermes.so
  third_party/rn/armeabi-v7a/libjsi.so
  third_party/rn/react_native.BUILD
  third_party/rn/x86/libhermes.so
  third_party/rn/x86/libjsi.so
  third_party/rn/x86_64/libhermes.so
  third_party/rn/x86_64/libjsi.so
  vitest.config.mts
Labels: patch

#618 Async node constructor consistency
  docs/site/src/content/docs/plugins/multiplatform/async-node.mdx
  plugins/async-node/core/src/__tests__/index.test.ts
  plugins/async-node/core/src/index.ts
  plugins/async-node/ios/Sources/AsyncNodePlugin.swift
  plugins/async-node/ios/Tests/AsynNodePluginTests.swift
  plugins/async-node/jvm/src/main/kotlin/com/intuit/playerui/plugins/asyncnode/AsyncNodePlugin.kt
  plugins/async-node/jvm/src/test/kotlin/com/intuit/playerui/plugins/asyncnode/AsyncNodePluginTest.kt
Labels: patch

#633 move renderIntoPlayerCanvas onto the correct thread
  android/player/src/main/java/com/intuit/playerui/android/ui/PlayerFragment.kt
  jvm/hermes/src/main/kotlin/com/intuit/playerui/hermes/extensions/Lock.kt
Labels: patch

#634 remove runtime specification
  .circleci/config.yml
Labels: skip-release

#614 Template ordering
  .gitignore
  PlayerUI.podspec
  core/player/src/view/builder/index.test.ts
  core/player/src/view/builder/index.ts
  core/player/src/view/parser/types.ts
  core/player/src/view/plugins/__tests__/__snapshots__/template.test.ts.snap
  core/player/src/view/plugins/__tests__/template.test.ts
  core/player/src/view/plugins/template.ts
  core/types/src/index.ts
  docs/site/src/content/docs/content/assets-views.mdx
  plugins/markdown/core/src/__tests__/helpers/index.ts
  plugins/markdown/core/src/__tests__/index.test.ts
Labels: minor
