Repository player-ui/player, pull requests merged in 2025-07, with the labels that each got.

#671 feat(common-expressions): add substr and split string functions
  docs/site/src/content/docs/plugins/core/common-expressions.mdx
  plugins/common-expressions/core/src/expressions/__tests__/expressions.test.ts
  plugins/common-expressions/core/src/expressions/index.ts
  plugins/common-expressions/core/src/index.ts
Labels: patch

#670 fix issues with react 18 suspense
  BUILD.bazel
  justfile
  package.json
  pnpm-lock.yaml
  react/player/src/__tests__/hooks.test.tsx
  react/player/src/manager/managed-player.tsx
  react/subscribe/BUILD
  react/subscribe/src/index.test.ts
  react/subscribe/src/index.test.tsx
  react/subscribe/src/index.tsx
Labels: patch

#677 Revert "Asset deprecation (#639)"
  android/demo/src/main/java/com/intuit/playerui/android/reference/demo/lifecycle/DemoPlayerViewModel.kt
  android/player/BUILD
  android/player/src/main/java/com/intuit/playerui/android/AndroidPlayer.kt
  android/player/src/main/java/com/intuit/playerui/android/asset/DecodableAsset.kt
  android/player/src/main/java/com/intuit/playerui/android/asset/RenderableAsset.kt
  android/player/src/main/java/com/intuit/playerui/android/asset/SuspendableAsset.kt
  android/player/src/main/java/com/intuit/playerui/android/compose/ComposableAsset.kt
  android/player/src/main/java/com/intuit/playerui/android/ui/PlayerFragment.kt
  android/player/src/test/java/com/intuit/playerui/android/renderer/BrokenAssetTest.kt
  android/player/src/test/java/com/intuit/playerui/android/renderer/HydrationScopeTest.kt
  android/player/src/test/java/com/intuit/playerui/android/renderer/NestedAssetTest.kt
  android/player/src/test/java/com/intuit/playerui/android/renderer/SimpleAssetTest.kt
  android/player/src/test/java/com/intuit/playerui/android/utils/BrokenAsset.kt
  android/player/src/test/java/com/intuit/playerui/android/utils/NestedAsset.kt
  android/player/src/test/java/com/intuit/playerui/android/utils/OtherSimpleAsset.kt
  android/player/src/test/java/com/intuit/playerui/android/utils/SimpleAsset.kt
  android/testutils/src/main/java/com/intuit/playerui/android/testutils/asset/Assertions.kt
  android/testutils/src/main/java/com/intuit/playerui/android/testutils/asset/AssetTest.kt
  docs/site/src/content/docs/assets/custom.mdx
  plugins/reference-assets/android/src/androidTest/java/com/intuit/playerui/android/reference/assets/action/ActionTest.kt
  plugins/reference-assets/android/src/androidTest/java/com/intuit/playerui/android/reference/assets/info/InfoTest.kt
  plugins/reference-assets/android/src/androidTest/java/com/intuit/playerui/android/reference/assets/input/InputTest.kt
  plugins/reference-assets/android/src/main/java/com/intuit/playerui/android/reference/assets/action/Action.kt
  plugins/reference-assets/android/src/main/java/com/intuit/playerui/android/reference/assets/info/Info.kt
  plugins/reference-assets/android/src/main/java/com/intuit/playerui/android/reference/assets/input/Input.kt
  plugins/reference-assets/android/src/main/java/com/intuit/playerui/android/reference/assets/text/Text.kt
Labels: minor

#682 update codeowners file with teams
  .github/CODEOWNERS
Labels: skip-release

#685 Build Tweaks
  .circleci/config.yml
Labels: skip-release

#695 Fix iOS Build Stage
  .circleci/config.yml
Labels: skip-release
