Repository player-ui/player, pull requests merged in 2025-02, with the labels that each got.

#584 Update to explicitly call out the default value for dataPath
  docs/site/src/content/docs/plugins/multiplatform/shared-constants.mdx
Labels: patch, skip-release

#592 Update CODEOWNERS
  .github/CODEOWNERS
Labels: skip-release

#572 Data change listener fix
  plugins/common-expressions/core/src/expressions/index.ts
  plugins/data-change-listener/core/BUILD
  plugins/data-change-listener/core/package.json
  plugins/data-change-listener/core/src/__tests__/index.test.ts
  pnpm-lock.yaml
Labels: patch

#596 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: skip-release

#598 Hermes perf optimization
  jvm/core/src/main/kotlin/com/intuit/playerui/core/bridge/serialization/serializers/NodeSerializableFunction.kt
  jvm/core/src/main/kotlin/com/intuit/playerui/core/constants/ConstantsController.kt
  jvm/core/src/main/kotlin/com/intuit/playerui/core/data/DataController.kt
  jvm/core/src/main/kotlin/com/intuit/playerui/core/data/DataModelWithParser.kt
  jvm/core/src/main/kotlin/com/intuit/playerui/core/expressions/ExpressionEvaluator.kt
  jvm/core/src/main/kotlin/com/intuit/playerui/core/flow/FlowController.kt
  jvm/core/src/main/kotlin/com/intuit/playerui/core/flow/FlowInstance.kt
  jvm/core/src/main/kotlin/com/intuit/playerui/core/logger/TapableLogger.kt
  jvm/core/src/main/kotlin/com/intuit/playerui/core/player/state/PlayerFlowState.kt
  jvm/core/src/main/kotlin/com/intuit/playerui/core/validation/BindingInstance.kt
  jvm/core/src/main/kotlin/com/intuit/playerui/core/validation/Validation.kt
  jvm/core/src/main/kotlin/com/intuit/playerui/core/validation/ValidationController.kt
  jvm/core/src/main/kotlin/com/intuit/playerui/core/validation/ValidationResponse.kt
  jvm/core/src/test/kotlin/com/intuit/playerui/core/data/DataControllerTest.kt
  jvm/core/src/test/kotlin/com/intuit/playerui/core/player/state/CompletedStateTest.kt
  plugins/beacon/jvm/src/main/kotlin/com/intuit/playerui/plugins/beacon/BeaconPlugin.kt
Labels: patch
