Repository player-ui/player, pull requests merged in 2025-03, with the labels that each got.

#608 Update CODEOWNERS File
  .github/CODEOWNERS
Labels: skip-release

#613 enable blocking logs by default
  jvm/core/src/main/kotlin/com/intuit/playerui/core/player/HeadlessPlayer.kt
Labels: patch

#611 chat ui storybook
  core/player/src/view/resolver/index.ts
  core/player/src/view/resolver/utils.ts
  docs/site/src/content/docs/plugins/multiplatform/async-node.mdx
  docs/storybook/BUILD
  docs/storybook/package.json
  docs/storybook/src/reference-assets/ChatUI.stories.tsx
  plugins/async-node/core/src/__tests__/index.test.ts
  plugins/reference-assets/mocks/chat-message/chat-ui.tsx
  pnpm-lock.yaml
  tools/storybook/src/dsl/createDSLStory.tsx
  tools/storybook/src/player/PlayerStory.tsx
Labels: patch

#615 Doc Site Updates
  docs/site/astro.config.mjs
  docs/site/src/components/NavBar.astro
  docs/site/src/components/Sidebar.astro
  docs/site/src/components/tools/VersionSelector.tsx
  docs/site/src/content/docs/content/data-expressions.mdx
  docs/site/src/content/docs/guides/multi-flow-experiences.mdx
  docs/site/src/styles/custom.css
  docs/site/src/tailwind.css
  plugins/reference-assets/react/src/components/Button.tsx
Labels: skip-release

#609 Jetpack Compose
  .gitignore
  MODULE.bazel
  android/demo/README.md
  android/demo/deps.bzl
  android/demo/src/androidTest/java/com/intuit/playerui/android/reference/demo/test/MainActivityTest.kt
  android/demo/src/androidTest/java/com/intuit/playerui/android/reference/demo/test/assets/action/ActionUITest.kt
  android/demo/src/androidTest/java/com/intuit/playerui/android/reference/demo/test/assets/badge/BadgeUITest.kt
  android/demo/src/androidTest/java/com/intuit/playerui/android/reference/demo/test/assets/collection/CollectionUITest.kt
  android/demo/src/androidTest/java/com/intuit/playerui/android/reference/demo/test/assets/info/InfoUITest.kt
  android/demo/src/androidTest/java/com/intuit/playerui/android/reference/demo/test/assets/input/InputUITest.kt
  android/demo/src/androidTest/java/com/intuit/playerui/android/reference/demo/test/base/Assertions.kt
  android/demo/src/androidTest/java/com/intuit/playerui/android/reference/demo/test/base/AssetUITest.kt
  android/demo/src/androidTest/java/com/intuit/playerui/android/reference/demo/test/base/ComposeUITest.kt
  android/demo/src/androidTest/java/com/intuit/playerui/android/reference/demo/test/fragment/PlayerFragmentScrollingTest.kt
  android/demo/src/main/AndroidManifest.xml
  android/player/BUILD
  android/player/deps.bzl
  android/player/src/main/java/com/intuit/playerui/android/AndroidPlayer.kt
  android/player/src/main/java/com/intuit/playerui/android/AssetContext.kt
  android/player/src/main/java/com/intuit/playerui/android/asset/RenderableAsset.kt
  android/player/src/main/java/com/intuit/playerui/android/compose/AssetStyle.kt
  android/player/src/main/java/com/intuit/playerui/android/compose/ComposableAsset.kt
  android/testutils/src/main/java/com/intuit/playerui/android/testutils/asset/Assertions.kt
  docs/site/src/content/docs/assets/custom.mdx
  justfile
  plugins/reference-assets/android/BUILD
  plugins/reference-assets/android/defs.bzl
  plugins/reference-assets/android/src/androidTest/java/com/intuit/playerui/android/reference/assets/action/ActionTest.kt
  plugins/reference-assets/android/src/androidTest/java/com/intuit/playerui/android/reference/assets/chatmessageasset/ChatMessageAssetTest.kt
  plugins/reference-assets/android/src/androidTest/java/com/intuit/playerui/android/reference/assets/collection/CollectionTest.kt
  plugins/reference-assets/android/src/androidTest/java/com/intuit/playerui/android/reference/assets/info/InfoTest.kt
  plugins/reference-assets/android/src/androidTest/java/com/intuit/playerui/android/reference/assets/input/InputTest.kt
  plugins/reference-assets/android/src/androidTest/java/com/intuit/playerui/android/reference/assets/text/TextTest.kt
  plugins/reference-assets/android/src/main/AndroidManifest.xml
  plugins/reference-assets/android/src/main/java/com/intuit/playerui/android/reference/assets/ReferenceAssetsPlugin.kt
  plugins/reference-assets/android/src/main/java/com/intuit/playerui/android/reference/assets/XmlStyleParser.kt
  plugins/reference-assets/android/src/main/java/com/intuit/playerui/android/reference/assets/action/Action.kt
  plugins/reference-assets/android/src/main/java/com/intuit/playerui/android/reference/assets/badge/Badge.kt
  plugins/reference-assets/android/src/main/java/com/intuit/playerui/android/reference/assets/collection/Collection.kt
  plugins/reference-assets/android/src/main/res/layout/collection.xml
  plugins/reference-assets/android/src/main/res/values/ids.xml
  plugins/reference-assets/android/src/main/res/values/text.xml
  plugins/reference-assets/mocks/badge/badge-all.json
Labels: minor

#620 Update Bazel Docker Image
  .circleci/config.yml
Labels: skip-release
