Repository player-ui/player, pull requests merged in 2025-08, with the labels that each got.

#697 add option to report unused disable directives in eslint
  core/player/src/binding-grammar/__tests__/ebnf/index.ts
  core/player/src/binding-grammar/custom/index.ts
  core/player/src/binding/utils.ts
  core/player/src/controllers/data/utils.ts
  core/player/src/expressions/parser.ts
  core/types/src/index.ts
  eslint.config.mts
  plugins/beacon/core/src/beacon.ts
  plugins/common-types/core/src/formats/__tests__/formats.test.ts
  plugins/pubsub/core/src/pubsub.ts
  plugins/reference-assets/core/src/assets/chat-message/transform.ts
  react/player/src/player.tsx
Labels: skip-release

#694 improve async node flattening and apply resolver cache to async nodes
  core/player/src/view/__tests__/view.test.ts
  core/player/src/view/builder/index.ts
  core/player/src/view/parser/index.ts
  core/player/src/view/parser/types.ts
  core/player/src/view/plugins/__tests__/multi-node.test.ts
  core/player/src/view/plugins/multi-node.ts
  core/player/src/view/resolver/__tests__/index.test.ts
  core/player/src/view/resolver/index.ts
  core/player/src/view/view.ts
  docs/site/src/content/docs/plugins/multiplatform/async-node.mdx
  plugins/async-node/core/src/__tests__/__snapshots__/transform.test.ts.snap
  plugins/async-node/core/src/__tests__/createAsyncTransform.test.ts
  plugins/async-node/core/src/__tests__/index.test.ts
  plugins/async-node/core/src/__tests__/transform.bench.ts
  plugins/async-node/core/src/createAsyncTransform.ts
  plugins/async-node/core/src/index.ts
  plugins/async-node/core/src/transform.ts
  plugins/async-node/core/src/types.ts
  plugins/async-node/core/src/utils/__tests__/extractNodeFromPath.test.ts
  plugins/async-node/core/src/utils/__tests__/traverseAndReplace.test.ts
  plugins/async-node/core/src/utils/__tests__/unwrapAsset.test.ts
  plugins/async-node/core/src/utils/extractNodeFromPath.ts
  plugins/async-node/core/src/utils/index.ts
  plugins/async-node/core/src/utils/traverseAndReplace.ts
  plugins/async-node/core/src/utils/unwrapAsset.ts
  plugins/reference-assets/core/src/assets/chat-message/transform.ts
Labels: minor

#706 Document common iOS Cache error and how to fix it
  ios/README.md
Labels: skip-release

#708 update createAsyncTransform to allow for different node types
  core/player/src/view/resolver/__tests__/index.test.ts
  plugins/async-node/core/src/__tests__/createAsyncTransform.test.ts
  plugins/async-node/core/src/createAsyncTransform.ts
  plugins/async-node/core/src/utils/__tests__/requiresAssetWrapper.test.ts
  plugins/async-node/core/src/utils/index.ts
  plugins/async-node/core/src/utils/requiresAssetWrapper.ts
Labels: patch

#707 Docs: Adding pages for complexity and metrics plugins, fixing redirects, restoring getting-started content
  docs/site/astro.config.mjs
  docs/site/src/content/docs/getting-started.mdx
  docs/site/src/content/docs/plugins/language/complexity-check.mdx
  docs/site/src/content/docs/plugins/language/metrics-output.mdx
Labels: documentation, patch
